input: touchscreen: fts_spi: Correct a bool cast error
 * So this should be a int parameter. Why xiaomi implement it as a bool
   in the focaltech touchscreen driver?

 * This should fix:

error: incompatible function pointer types assigning to 'int (*)(int)' from 'int (bool)' (aka 'int (_Bool)') [-Werror,-Wincompatible-function-pointer-types]
        xiaomi_touch_interfaces.enable_touch_raw = fts_enable_touch_raw;
                                                 ^ ~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: EndCredits <endcredits@crepuscular-aosp.icu>